### ISSUE TITLE
Configure alerts for ODF in external ceph mode

### ISSUE THREAD

**Issue by jtriley** [OCP-on-NERC/operations#39]
This is related #38 - it would be nice to have alerting when we get close to the ceph pool quota limit.

However, it appears ODF doesn't configure alerts for external mode ceph:

> For internal Mode clusters, various alerts related to the storage metrics services, storage cluster, disk devices, cluster health, cluster capacity, and so on are displayed in the Block and File, and the object dashboards. These alerts are not available for external Mode.

see: https://access.redhat.com/documentation/en-us/red_hat_openshift_data_foundation/4.10/html/monitoring_openshift_data_foundation/alerts

We might need to push our own ceph metrics via a custom deployment and setup alerts from observability assuming we don't get this for free from ODF.

**Comment by computate** [comment]
We now have alerts for ceph storage when it's filled > 80% with this pull request here https://github.com/OCP-on-NERC/nerc-ocp-config/pull/184

**Comment by larsks** [comment]
I am reopening this because recent events demonstrate that we're not currently monitoring the appropriate metrics. In particular, while there are existing metrics that cover capacity used and capacity requested, there are no metrics relating to the Ceph quota.

@naved001 suggests in [an earlier comment](https://github.com/OCP-on-NERC/operations/issues/39#issuecomment-1319325230) how we can extract the necessary information, and I think that writing a simple prometheus compatible metrics collector for that would be relatively easy.

It's also possible that there already exists a Ceph metrics collector that we can run external to Ceph that may provide the necessary metrics "out of the box".

**Comment by computate** [comment]
I have added alerts for Ceph storage filling up, and also Ceph storage predicted to fill up based on actual Ceph metrics in this PR: 
https://github.com/OCP-on-NERC/nerc-ocp-config/pull/229
